drop table if exists user_meeting_room cascade ;
drop table if exists reserv_info cascade ;

create table if not exists user_meeting_room(
    user_id int generated  by default as identity primary key ,
    name varchar(255) not null,
    password varchar(255) not null unique

);

create table if not exists reserv_info(
    reserv_id integer generated by default as identity primary key ,
    start_time varchar(255) not null ,
    stop_time varchar(255) not null,
    reserv_date varchar(255) not null ,
    user_id int not null ,
    foreign key (user_id) references user_meeting_room(user_id)
);